version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8055:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "123"
      WORDPRESS_DB_NAME: wordpress
    networks:
      temshop:
        ipv4_address: "192.168.2.2"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  temshop:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"
